# Generated by Django 5.1.1 on 2024-09-27 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='work/%Y/%m', verbose_name='Фото')),
                ('photo_minified', models.ImageField(blank=True, null=True, upload_to='work_mini/%Y/%m', verbose_name='Стиснуте фото для мобільних пристроїв')),
                ('alt_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис для фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фотографії',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Підзаголовок')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('photo_minified', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Стиснуте фото')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='Підпис')),
                ('date_start', models.DateTimeField(blank=True, verbose_name='Розпочато')),
                ('date_end', models.DateTimeField(blank=True, verbose_name='Закінчено')),
                ('client', models.CharField(blank=True, max_length=150, verbose_name='Роботодавець')),
                ('job', models.CharField(blank=True, max_length=150, verbose_name='Посада')),
                ('content', models.TextField(blank=True, verbose_name='Вміст')),
                ('is_main', models.BooleanField(default=True, verbose_name='На головну')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
                ('slide', models.ManyToManyField(blank=True, to='Work.photo', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головні сторінки',
                'ordering': ['-order', '-date_end', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Черга')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.photo', verbose_name='Фото')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.work', verbose_name='Робота')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
    ]
