# Generated by Django 5.1.1 on 2024-09-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-order', '-date_end', 'title'], 'verbose_name': 'Проєкт', 'verbose_name_plural': 'Проєкти'},
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Work.photo', verbose_name='Фото карусель'),
        ),
    ]
