# Generated by Django 5.1.1 on 2024-10-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0002_alter_work_options_alter_carouselitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='work',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
