# Generated by Django 5.1.1 on 2024-10-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work', '0003_work_slug_work_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='alt_text',
            field=models.CharField(blank=True, max_length=250, verbose_name='Підпис для фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='work/%Y/%m', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='work',
            name='photo_minified',
            field=models.ImageField(blank=True, null=True, upload_to='work_mini/%Y/%m', verbose_name='Стиснуте фото'),
        ),
    ]
