# Generated by Django 5.0.3 on 2024-03-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-mail')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Телефон')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
            ],
            options={
                'verbose_name': 'Контакти',
                'verbose_name_plural': 'Контакти',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('photo_minified', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Стиснуте фото')),
                ('alt_text', models.CharField(blank=True, max_length=250, verbose_name='Підпис')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Іконка')),
                ('cv', models.FileField(blank=True, upload_to='uploads/')),
                ('portfolio', models.FileField(blank=True, upload_to='uploads/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Підпис')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
            ],
            options={
                'verbose_name': 'Головна сторінка',
                'verbose_name_plural': 'Головні сторінки',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='E-mail')),
                ('subject', models.CharField(blank=True, max_length=150, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Вміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено коли')),
            ],
            options={
                'verbose_name': 'Форма контакту',
                'verbose_name_plural': 'Форми контакту',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Підпис для іконки мережі')),
                ('text', models.TextField(blank=True, verbose_name='Опис')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
            ],
            options={
                'verbose_name': 'Секція',
                'verbose_name_plural': 'Сеції',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Назва')),
                ('url', models.URLField(verbose_name='Посилання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікувати')),
            ],
            options={
                'verbose_name': 'Зовнішнє посилання',
                'verbose_name_plural': 'Зовішні посилання',
                'ordering': ['title'],
            },
        ),
    ]
