# Generated by Django 5.1.1 on 2024-09-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['title'], 'verbose_name': 'Секція', 'verbose_name_plural': 'Секції'},
        ),
    ]
