# Generated by Django 5.1.1 on 2024-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0003_alter_contacts_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Іконка'),
        ),
    ]
