# Generated by Django 5.1.1 on 2024-10-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0004_social_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Іконка (дві літери)'),
        ),
    ]
