# Generated by Django 5.1.1 on 2024-11-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0009_alter_section_options_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='section_id',
        ),
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(max_length=150, null=True, verbose_name='Слаг'),
        ),
    ]
