# Generated by Django 5.1.1 on 2024-11-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0010_remove_section_section_id_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='alt_banner_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Підпис'),
        ),
        migrations.AddField(
            model_name='main',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Банер'),
        ),
        migrations.AddField(
            model_name='main',
            name='banner_minified',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Стиснутий банер'),
        ),
    ]
