# Generated by Django 5.1.1 on 2024-11-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_n_Settings', '0011_main_alt_banner_text_main_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='main',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на портфоліо'),
        ),
    ]
