name: Deploy Django to Hyperhost cPanel

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files with rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: >-
            -avzr --delete
            --exclude=.git
            --exclude=.github
            --exclude=venv
            --exclude=.env
            --exclude=.htaccess
            --exclude=cgi-bin
            --exclude=public
            --exclude=stderr.log
            --exclude=tmp
            --exclude=db.sqlite3
            --exclude=media
            --exclude=__pycache__
            --exclude=passenger_wsgi.py
          path: ./
          remote_path: ${{ secrets.CPANEL_PROJECT_PATH }}/
          remote_host: ${{ secrets.CPANEL_HOST }}
          remote_user: ${{ secrets.CPANEL_USER }}
          remote_port: ${{ secrets.CPANEL_PORT }}
          remote_key: ${{ secrets.CPANEL_SSH_KEY }}
          excludes: |
            .git
            .github
            venv
            .env
            db.sqlite3
            media
            tmp
            __pycache__
            .htaccess
            passenger_wsgi.py
            stderr.log
            cgi-bin
            public

      - name: Run server deployment commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          port: ${{ secrets.CPANEL_PORT }}
          script: |
            source /home/${{ secrets.CPANEL_USER }}/virtualenv/myport/3.11/bin/activate
      
            cd ${{ secrets.CPANEL_PROJECT_PATH }}
      
            pip install -r requirements.txt
      
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
      
            mkdir -p tmp
            touch tmp/restart.txt
